export const ACTIVITY_TYPES = {
    // User activities
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',

    // Teacher activities
    TEACHER_CREATED: 'TEACHER_CREATED',
    TEACHER_UPDATED: 'TEACHER_UPDATED',
    TEACHER_DELETED: 'TEACHER_DELETED',

    // Student activities
    STUDENT_CREATED: 'STUDENT_CREATED',
    STUDENT_UPDATED: 'STUDENT_UPDATED',
    STUDENT_DELETED: 'STUDENT_DELETED',

    // Exam activities
    EXAM_CREATED: 'EXAM_CREATED',
    EXAM_UPDATED: 'EXAM_UPDATED',
    EXAM_DELETED: 'EXAM_DELETED',

    // Timetable activities
    TIMETABLE_CREATED: 'TIMETABLE_CREATED',
    TIMETABLE_UPDATED: 'TIMETABLE_UPDATED',
    TIMETABLE_DELETED: 'TIMETABLE_DELETED',
    TIMETABLE_ENTRY_ADDED: 'TIMETABLE_ENTRY_ADDED',
    TIMETABLE_ENTRY_REMOVED: 'TIMETABLE_ENTRY_REMOVED',

    // Announcement activities
    ANNOUNCEMENT_CREATED: 'ANNOUNCEMENT_CREATED',
    ANNOUNCEMENT_REMOVED: 'ANNOUNCEMENT_REMOVED'
};